
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 12 23:05:53 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_MeQ = 6;
  public static final int Op_And = 3;
  public static final int MENOS = 15;
  public static final int DECIMAL = 13;
  public static final int Op_MeIQ = 8;
  public static final int Op_Not = 4;
  public static final int POT = 18;
  public static final int ID = 11;
  public static final int Op_Or = 2;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int PAR_IZQ = 19;
  public static final int Op_MaQ = 5;
  public static final int error = 1;
  public static final int PAR_DER = 20;
  public static final int Op_Sem = 10;
  public static final int ENTERO = 12;
  public static final int MAS = 14;
  public static final int Op_Dif = 9;
  public static final int Op_MaIQ = 7;
}

